version: '3.7'

services:
  nginx:
    depends_on:
      - api
      - web
      - web-prod
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
  api:
    build:
      context: ../../python-flask/settle-regulation-torch-pythonflask
      dockerfile: Dockerfile
    ports:
      - '1414:5000'
  web:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app
  web-prod:
    container_name: my-app-prod
    build: .
    ports:
      - '1337:80'
